### ISSUE TITLE
New Color Setting Type Options

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-ts-definition#32]
* Ability to predefine colors to pick from (could be a select but better?)
* Ability to use the system colors (needs to be defined/provided by Rocket.Chat)

**Comment by rodrigok** [comment]
Issue moved to [RocketChat/Rocket.Chat.Apps-engine #51](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/51) via [**ZenHub**](https://www.zenhub.com/)
