### ISSUE TITLE
Add Instance Documentation

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-ts-definition#34]
Add documentation which states that storing items in memory inside of the App is not recommended at all because a Rocket.Chat server can have several instances and each server has its own instance of an app. If the data, such as confirmation for context, needs to be shared between the different instances then the persistence accessor needs to be used.

**Comment by rodrigok** [comment]
Issue moved to [RocketChat/Rocket.Chat.Apps-engine #52](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/52) via [**ZenHub**](https://www.zenhub.com/)
