### ISSUE TITLE
Message Additions

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-ts-definition#44]
Allow Apps to provide message attachments/uploads.

![image](https://user-images.githubusercontent.com/850391/39647715-ab28d996-4fa5-11e8-9a54-c021ee369670.png)

**Comment by rodrigok** [comment]
Issue moved to [RocketChat/Rocket.Chat.Apps-engine #55](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/55) via [**ZenHub**](https://www.zenhub.com/)
