### ISSUE TITLE
Allow Dependencies on npm Packages

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-ts-definition#49]
Currently Apps can not bring in third party packages in a supported manner (yes there are ways around it), however this is a big need and if we don't allow this then Apps will be severely limited. However, just allowing Apps to include any and every npm package will open the door to security issues and even malware packages.

So, we need a way to provide "secure" way for Apps to define the npm packages they use. This will be a multi-step process. First up, we will add a `npmDepends` configuration section of the `App.json` configuration file. Then whenever someone submits an App to the Marketplace we will look through that section and ensure they seem to be trusted modules. After it has been marked as reviewed and "trusted", an automated system will package in the npm modules (we will need to look into the license restrictions here) into the App.

However, there will be Apps that want to not distribute themselves via the Marketplace for various reasons (let's say an in-house App). Due to this, we will provide a way for Apps to package the npm modules themselves but a big, not so nice, warning will be displayed when installing and enabling the App that warns of potential risks associated with that App.

---

I would like the thoughts of any and everyone on this manner. Does this make sense and is it logical to do this? Yes, the Apps Marketplace will already have a manual review process so adding one more task to it just makes sense.

**Comment by JSzaszvari** [comment]
@timkinnane Agreed ++

**Comment by graywolf336** [comment]
Thanks for the input guys :+1: we will keep this in mind when actually starting to work on this. :)

**Comment by graywolf336** [comment]
To do: Evaluate how vscode's extension manifest (as the App.json was influenced by it) https://code.visualstudio.com/docs/extensionAPI/extension-manifest

**Comment by rodrigok** [comment]
Issue moved to [RocketChat/Rocket.Chat.Apps-engine #56](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/56) via [**ZenHub**](https://www.zenhub.com/)
