### ISSUE TITLE
Logging per Rocketlet

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-ts-definition#8]
One of the reasons the current integrations inside of Rocket.Chat are hard to develop against and debug is because the log messages are merged with the rest of the logging system.

A few requirements I would like to see the Rocketlets have for logging:

- Separated from the the rest of Rocket.Chat
- Logs per run of any method (when a debugging mode is enabled)
- Logs viewable per level type
- Overall view of logs

The interface for viewing logs would ideally be searchable, filterable, and all of that (putting this here more for future reference).

**Comment by mrsimpson** [comment]
very important point, indeed!
I'd expect a "sandbox `console`" which is parametrized to write to an own log file would be established for each Rocketlet.
This console should be available at runtime globally within the scope of the Rocketlet.
